# Generated by Django 2.1.4 on 2019-03-20 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doughy', models.IntegerField(verbose_name='金额/元')),
                ('ofconsumption_date', models.DateField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='Ofconsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='消费类型')),
                ('income_or_outlay', models.IntegerField(choices=[(1, '支出'), (2, '收入')], verbose_name='支出或收入')),
            ],
        ),
        migrations.AddField(
            model_name='charge',
            name='ofconsumption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.Ofconsumption'),
        ),
    ]
