# Generated by Django 2.1.4 on 2019-03-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofconsumption',
            name='icon',
            field=models.CharField(default='shopping_basket', max_length=32, verbose_name='图标'),
        ),
    ]
